# we need to create this file by ourself
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
data:
### Solution that map to the single file
  default.json: |
    {
      "network": {
        "port": 80
      },
      "environment": {
        "SSL": false
      }, 
      "redis": {
        "server": "{{ .Release.Name }}-redis-master",
        "port": "6379"
      }
    }