{{- $ports := .Values.service.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  annotations:
    mainPort: "{{ (index .Values.service.ports 0).number }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := $ports }}
  {{- if and (eq ($value.number | int) 8080) (eq $value.name "admin") }}
  {{- fail "Please ise another port number than 8080 for the admin port " }}
  {{- end -}}
    - port: {{ .number }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      name: {{ .name }}
  {{- end }}   

    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    #   # added a new port from values.yaml
    # - port: {{ .Values.service.ssl_port }}
    #   targatPort: {{ .Values.service.ssl_target_port }}
    #   name: {{ .Values.service.ssl_name }}
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
