# we need to create this file by ourself
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
data:
 default.json: |
    {
      "network": {
        "port": 80
      },
      "environment": {
        "SSL": false
      },
      "redis": {
        "server": "{{ .Release.Name }}-redis-master",
        "port": "6379"
      }
    }



# .Files.Glob is returning files and it is depends from us how we want to use it
{{- /*

### Solution that map to the single file
  default.json: |
{{ .Files.Get "default.json" | indent 4 }}

---------------------------

  this is helm's comment. if i will comment it out following yaml fiule
  helm still would read it and give me error ! 
 {{ .Files.Glob "config/*" | indent 4 }}


 {{ (.Files.Glob "config/*").AsConfig | indent 4 }}
*/}}












